### ISSUE TITLE
file Icons are aligned to top of tab

### ISSUE THREAD

**Issue by arda-** [sveale/remote-edit#167]
When using the package [file icons](https://atom.io/packages/file-icons), the icons seem to be aligned to the top of the tab instead of the window. This occurs with many different file types.

Here are a variety of remotely opened files:
<img width="807" alt="screen shot 2016-02-03 at 11 00 00 am" src="https://cloud.githubusercontent.com/assets/9686548/12793579/27147bea-ca66-11e5-93f3-3f750820d6fb.png">

Here is a remotely opened file next to a local one:
<img width="482" alt="screen shot 2016-02-03 at 11 05 29 am" src="https://cloud.githubusercontent.com/assets/9686548/12793580/2735a9a0-ca66-11e5-95c6-19cebf53a14c.png">

Not quite sure whether this is an issue more appropriate for your project, or the other! I posted to both, just in case.

**Comment by sdbarron** [comment]
A local file has only a class of "title" while a remote-edit item has "title icon icon-globe".  It seems as if remote-edit is trying to do icon functionality (which sounds good) but it's incompatible with at least this other icon package.

**Comment by Alhadis** [comment]
Yup, patched.

@sveale You can prevent styling tabs by wrapping the CSS in this:

```less
body:not(.file-icons-tab-pane-icon){

	.icon-globe::before{
		font-family: 'Octicons Regular';
		font-weight: normal;
		font-style: normal;
		display: inline-block;
		line-height: 1;
		-webkit-font-smoothing: antialiased;
		text-decoration: none;
		font-size: 16px;
		width: 16px;
		height: 16px;
		content: "\f0b6";
	}
}
```
